sudo apt install nmap 
sudo apt install whois
sudo apt install traceroute
sudo apt install dnsutils
sudo apt install whatweb
sudo apt install wpscan
sudo apt install nikto
sudo apt install nbtscan
sudo apt install smbclient
sudo apt install enum4linux